version: '3'
services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
        - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "5466:5432"